---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-admission-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-admission-controller
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-admission-controller
    namespace: {{ .Release.Namespace }}
