---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-admission-controller
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/issuer: {{ $.Release.Name }}-admission-controller
spec:
  replicas: {{ .Values.admissionController.replicas }}
  selector:
    matchLabels:
      app: admission-controller
  template:
    metadata:
      labels:
        app: admission-controller
    spec:
      serviceAccountName: {{ .Release.Name }}-admission-controller
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      containers:
        - name: admission-controller
          {{- with .Values.admissionController }}
          image: "k8s.gcr.io/autoscaling/vpa-admission-controller:{{ $.Chart.AppVersion }}"
          imagePullPolicy: Always
          args:
            - --port=8080
            - --address=:9090
            - --webhook-service={{ $.Release.Name }}-admission-controller
            - --client-ca-file=/tls-secret/ca.crt
            - --tls-cert-file=/tls-secret/tls.crt
            - --tls-private-key=/tls-secret/tls.key
            {{- range $key, $value := .extraArgs }}
            - --{{ $key }}={{ $value }}
            {{- end }}
          env:
            - name: NAMESPACE
              value: {{ $.Release.Namespace }}
          volumeMounts:
            - name: tls-secret
              mountPath: /tls-secret
              readOnly: true
          ports:
            - name: https
              protocol: TCP
              containerPort: 8080
            - name: metrics
              protocol: TCP
              containerPort: 9090
          resources:
            {{- with .resources }}
            requests:
              memory: {{ .requests.memory }}
              cpu: {{ .requests.cpu }}
            limits:
              memory: {{ .limits.memory }}
              cpu: {{ .limits.cpu }}
            {{- end }}
          startupProbe:
            httpGet:
              path: /health-check
              port: metrics
              scheme: HTTP
            periodSeconds: 1
            failureThreshold: 120
          readinessProbe:
            httpGet:
              path: /health-check
              port: metrics
              scheme: HTTP
            periodSeconds: 1
          livenessProbe:
            httpGet:
              path: /health-check
              port: metrics
              scheme: HTTP
          {{- end }}
      volumes:
        - name: tls-secret
          secret:
            secretName: {{ .Release.Name }}-admission-controller-tls
