---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-admission-controller
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: https
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: metrics
  selector:
    app: admission-controller
