---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-updater
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.updater.replicas }}
  selector:
    matchLabels:
      app: updater
  template:
    metadata:
      labels:
        app: updater
    spec:
      serviceAccountName: {{ .Release.Name }}-updater
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      containers:
        - name: updater
          {{- with .Values.updater }}
          image: "registry.k8s.io/autoscaling/vpa-updater:{{ $.Chart.AppVersion }}"
          imagePullPolicy: Always
          args:
            - --address=:9090
            {{- range $key, $value := .extraArgs }}
            - --{{ $key }}={{ $value }}
            {{- end }}
          env:
            - name: NAMESPACE
              value: {{ $.Release.Namespace }}
          ports:
            - name: metrics
              protocol: TCP
              containerPort: 9090
          resources:
            {{- with .resources }}
            requests:
              memory: {{ .requests.memory }}
              cpu: {{ .requests.cpu }}
            limits:
              memory: {{ .limits.memory }}
              cpu: {{ .limits.cpu }}
            {{- end }}
          startupProbe:
            httpGet:
              path: /health-check
              port: metrics
              scheme: HTTP
            periodSeconds: 1
            failureThreshold: 120
          readinessProbe:
            httpGet:
              path: /health-check
              port: metrics
              scheme: HTTP
            periodSeconds: 1
          livenessProbe:
            httpGet:
              path: /health-check
              port: metrics
              scheme: HTTP
          {{- end }}
